const test = require('node:test');
const assert = require('node:assert/strict');

const { readUtf8 } = require('./testHelpers.cjs');

test('core JS files keep expected symbols for game logic and progress', () => {
  const main = readUtf8('js/main.js');
  const ui = readUtf8('js/ui.js');
  const levels = readUtf8('js/levels.js');
  const textsUk = readUtf8('js/texts.uk.js');
  const gameState = readUtf8('js/gameState.js');
  const engineRoute = readUtf8('js/engineRoute.js');
  const engine = readUtf8('js/engine.js');
  const render = readUtf8('js/render.js');
  const renderDrag = readUtf8('js/renderDrag.js');
  const renderSnail = readUtf8('js/renderSnail.js');
  const uiAudio = readUtf8('js/uiAudio.js');
  const uiModals = readUtf8('js/uiModals.js');

  assert.ok(main.includes('resolveTileExit'));
  assert.ok(main.includes('app.oppositeDir'));
  assert.ok(main.includes('createTileDef'));
  assert.ok(main.includes('createTileIconByDir'));
  assert.ok(main.includes('iconFile'));
  assert.ok(main.includes('\\u0432\\u043b\\u0456\\u0432\\u043e \\u2192 \\u0432\\u0433\\u043e\\u0440\\u0443')); 
  assert.ok(main.includes('\\u0432\\u043f\\u0440\\u0430\\u0432\\u043e \\u2192 \\u0432\\u0433\\u043e\\u0440\\u0443')); 
  assert.ok(main.includes('\\u0432\\u043d\\u0438\\u0437 \\u2192 \\u0432\\u043f\\u0440\\u0430\\u0432\\u043e')); 
  assert.ok(main.includes('\\u0432\\u0433\\u043e\\u0440\\u0443 \\u2192 \\u0432\\u043b\\u0456\\u0432\\u043e')); 
  assert.ok(ui.includes('debugNoteEl'));
  assert.ok(ui.includes('setLevelIntroStatus'));
  assert.ok(ui.includes('refreshProgressUi'));
  assert.ok(ui.includes('earlyLevelInfoButton'));
  assert.ok(ui.includes('earlyLevelSpeakButton'));
  assert.ok(ui.includes('audioApi'));
  assert.ok(ui.includes('modalApi'));
  assert.ok(uiAudio.includes('createUiAudio'));
  assert.ok(uiAudio.includes('playSuccessSound'));
  assert.ok(uiAudio.includes('speakCurrentTask'));
  assert.ok(uiModals.includes('openLevelMap'));
  assert.ok(uiModals.includes('showWin'));
  assert.ok(uiModals.includes('restartProgress'));
  assert.ok(uiModals.includes('openManagedModal'));
  assert.ok(uiModals.includes('createModalCloseButton'));
  assert.ok(uiModals.includes('\u{1F389}')); 
  assert.ok(renderDrag.includes('createRenderDrag'));
  assert.ok(renderDrag.includes('beginPointerDrag'));
  assert.ok(renderDrag.includes('updateDropTarget'));
  assert.ok(renderDrag.includes('createTileIconByDir'));
  assert.ok(renderDrag.includes('ghostEl.replaceChildren'));
  assert.ok(!renderDrag.includes('ghostEl.innerHTML = icon'));
  assert.ok(renderSnail.includes('createRenderSnail'));
  assert.ok(renderSnail.includes('bumpSnail'));
  assert.ok(renderSnail.includes('posSnail'));
  assert.ok(render.includes('const dragApi = app.createRenderDrag'));
  assert.ok(render.includes('const snailApi = app.createRenderSnail'));
  assert.ok(render.includes('createTileIconElement'));
  assert.ok(!render.includes('arrowEl.innerHTML = def.icon'));
  assert.ok(!render.includes('button.innerHTML = icon'));
  assert.ok(levels.includes('ALL_TILES'));
  assert.ok(levels.includes('centerLevelLayout'));
  assert.ok(levels.includes('id: 20'));
  assert.ok(levels.includes('id: 19'));
  assert.ok(textsUk.includes('Пригоди Равлика')); 
  assert.ok(textsUk.includes('Тягни команди на поле')); 
  assert.ok(textsUk.includes('Що робити'));
  assert.ok(textsUk.includes('Пояснити завдання')); 
  assert.ok(gameState.includes('texts.uk.js must be loaded before gameState.js'));
  assert.ok(gameState.includes('app.text = app.textUk'));
  assert.ok(gameState.includes('ravlyk-code-progress-v1'));
  assert.ok(gameState.includes('saveProgress'));
  assert.ok(gameState.includes('loadProgress'));
  assert.ok(engine.includes('routeApi.resolveRouteStep'));
  assert.ok(engine.includes('routeApi.inspectForwardMove'));
  assert.ok(engineRoute.includes('findNeighborStartMove'));
  assert.ok(engineRoute.includes('analyzeCurrentRoute'));
  assert.ok(render.includes('preset-arrow'));
});

test('responsive UI and safe-delete styles remain present', () => {
  const ui = readUtf8('js/ui.js');
  const gameCss = readUtf8('css/game.css');
  const render = readUtf8('js/render.js');

  assert.ok(gameCss.includes('aspect-ratio: 8 / 6'));
  assert.ok(gameCss.includes('.level-card'));
  assert.ok(gameCss.includes('.cell-delete-btn'));
  assert.ok(gameCss.includes('pending-delete-wiggle'));
  assert.ok(gameCss.includes('.debug-note'));
  assert.ok(gameCss.includes('.progress-fill'));
  assert.ok(gameCss.includes('.level-map-grid'));
  assert.ok(gameCss.includes('.cell-arrow.preset-arrow'));
  assert.ok(render.includes('minmax(0, 1fr)'));
  assert.ok(render.includes('setActiveGridCell'));
  assert.ok(render.includes('ArrowRight'));
  assert.ok(render.includes("tabindex', '-1'"));
  assert.ok(ui.includes('registerServiceWorker'));
  assert.ok(ui.includes("navigator.serviceWorker.register('./sw.js')"));
  assert.ok(ui.includes("root.style.setProperty('--gs-w'"));
  assert.ok(ui.includes("root.style.setProperty('--gs-h'"));
  assert.ok(readUtf8('sw.js').includes('isSuccessfulDocumentResponse'));
  assert.ok(readUtf8('sw.js').includes('cacheDocumentResponse'));
  assert.ok(readUtf8('sw.js').includes("content-type"));
  assert.ok(readUtf8('sw.js').includes('response.ok'));
});


