const CACHE_VERSION = '2026-08-02-10';
// Precache (install-time assets) and runtime cache are kept separate so that
// trimRuntimeCache() can evict dynamic entries without touching precache URLs.
const APP_CACHE = `ravlyk-app-${CACHE_VERSION}`;
const RUNTIME_CACHE = `ravlyk-runtime-${CACHE_VERSION}`;
const OFFLINE_FALLBACK_URL = '/index.html';

// Maximum number of dynamically cached entries in RUNTIME_CACHE.
// Prevents unbounded cache growth if new URLs are fetched at runtime.
const MAX_RUNTIME_CACHE_ENTRIES = 250;

// Only cache same-origin responses for known static asset types.
// This prevents accidental caching of API responses, analytics pings,
// or any future dynamic endpoints added to the same origin.
// BEGIN GENERATED PRECACHE MANIFEST
// Generated by scripts/sync-precache-manifest.mjs from
// PAGES_PUBLICATION_MANIFEST.root. Do not edit this block manually.
const CACHEABLE_EXTENSIONS = new Set([
    '.html',
    '.css',
    '.js',
    '.mjs',
    '.svg',
    '.png',
    '.jpg',
    '.jpeg',
    '.webp',
    '.ico',
    '.webmanifest',
    '.woff',
    '.woff2',
]);

const PRECACHE_URLS = [
    '/',
    '/about.html',
    '/advice_for_parents.html',
    '/android-chrome-192x192.png',
    '/android-chrome-512x512.png',
    '/apple-touch-icon.png',
    '/assets/icons/arrow-left.svg',
    '/assets/icons/arrow-right.svg',
    '/assets/icons/book-open.svg',
    '/assets/icons/check-circle.svg',
    '/assets/icons/check.svg',
    '/assets/icons/copy.svg',
    '/assets/icons/download.svg',
    '/assets/icons/exclamation-triangle.svg',
    '/assets/icons/graduation-cap.svg',
    '/assets/icons/info-circle.svg',
    '/assets/icons/link.svg',
    '/assets/icons/paint-brush.svg',
    '/assets/icons/play.svg',
    '/assets/icons/puzzle-piece.svg',
    '/assets/icons/question-circle.svg',
    '/assets/icons/stop-circle.svg',
    '/assets/icons/th.svg',
    '/assets/icons/times.svg',
    '/assets/icons/trash-alt.svg',
    '/assets/icons/universal-access.svg',
    '/assets/images/editor.jpg',
    '/assets/images/lesson_01_01.jpg',
    '/assets/images/lesson_02_01.jpg',
    '/assets/images/lesson_03_01.jpg',
    '/assets/images/lesson_04_01.jpg',
    '/assets/images/lesson_05_01.jpg',
    '/assets/images/lesson_05_02.jpg',
    '/assets/images/lesson_06_01.jpg',
    '/assets/images/manual_01.jpg',
    '/assets/images/manual_02.jpg',
    '/assets/images/manual_03.jpg',
    '/assets/images/manual_04.jpg',
    '/assets/images/manual_05.jpg',
    '/assets/images/manual_06.jpg',
    '/assets/images/manual_07.jpg',
    '/assets/images/ravlyk.png',
    '/favicon-16x16.png',
    '/favicon-32x32.png',
    '/favicon.ico',
    '/index.html',
    '/js/modules/accessibilityNotifications.js',
    '/js/modules/accessibilitySettings.js',
    '/js/modules/backgroundLayer.js',
    '/js/modules/constants.js',
    '/js/modules/editorInputController.js',
    '/js/modules/editorUi.js',
    '/js/modules/environment.js',
    '/js/modules/executionController.js',
    '/js/modules/fileActionsController.js',
    '/js/modules/gifCapture.js',
    '/js/modules/gifEncoder.js',
    '/js/modules/gridOverlay.js',
    '/js/modules/interpreterAnimation.js',
    '/js/modules/interpreterAstAnimationRuntime.js',
    '/js/modules/interpreterAstEval.js',
    '/js/modules/interpreterAstQueueAdapter.js',
    '/js/modules/interpreterAstRuntime.js',
    '/js/modules/interpreterBoundary.js',
    '/js/modules/interpreterCommandClone.js',
    '/js/modules/interpreterCommandExecutor.js',
    '/js/modules/interpreterConditions.js',
    '/js/modules/interpreterDrawingOps.js',
    '/js/modules/interpreterEmbroidery.js',
    '/js/modules/interpreterGameAstRunner.js',
    '/js/modules/interpreterGameContract.js',
    '/js/modules/interpreterGameLoop.js',
    '/js/modules/interpreterLifecycleCleanup.js',
    '/js/modules/interpreterPrimitiveStatements.js',
    '/js/modules/interpreterQueueRuntime.js',
    '/js/modules/interpreterRuntimeState.js',
    '/js/modules/lessonsPageController.js',
    '/js/modules/lifecycleController.js',
    '/js/modules/manualPageController.js',
    '/js/modules/modalController.js',
    '/js/modules/navigationPrefetch.js',
    '/js/modules/parserBlocksConditions.js',
    '/js/modules/parserControlStatements.js',
    '/js/modules/parserCoreUtils.js',
    '/js/modules/parserCreateStatement.js',
    '/js/modules/parserExpressions.js',
    '/js/modules/parserMotionStatements.js',
    '/js/modules/parserStateStatements.js',
    '/js/modules/parserStatementContext.js',
    '/js/modules/parserStatementDispatcher.js',
    '/js/modules/parserStatementHandlers.js',
    '/js/modules/parserStatements.js',
    '/js/modules/parserTokenizer.js',
    '/js/modules/randomResolver.js',
    '/js/modules/ravlykInterpreter.js',
    '/js/modules/ravlykInterpreterRuntime.js',
    '/js/modules/ravlykParser.js',
    '/js/modules/semanticValidator.js',
    '/js/modules/share.js',
    '/js/modules/ui.js',
    '/js/modules/uiMessages.js',
    '/js/modules/uiModals.js',
    '/js/modules/workspaceTabs.js',
    '/js/quizBank.js',
    '/js/quizData/basic.js',
    '/js/quizData/loops.js',
    '/js/quizData/vars.js',
    '/lessons.html',
    '/manual.html',
    '/privacy.html',
    '/quiz.html',
    '/ravlyk.jpg',
    '/resources.html',
    '/teacher_guidelines.html',
    '/zen.html',
    '/css/about-project.css?v=2026-08-02-10',
    '/css/accessibility.css?v=2026-08-02-10',
    '/css/global.css?v=2026-08-02-10',
    '/css/lessons.css?v=2026-08-02-10',
    '/css/main-editor.css?v=2026-08-02-10',
    '/css/manual.css?v=2026-08-02-10',
    '/css/parents.css?v=2026-08-02-10',
    '/css/quiz.css?v=2026-08-02-10',
    '/css/resources.css?v=2026-08-02-10',
    '/css/teacher-guidelines.css?v=2026-08-02-10',
    '/css/zen.css?v=2026-08-02-10',
    '/js/accessibility.js?v=2026-08-02-10',
    '/js/lessonsPage.js?v=2026-08-02-10',
    '/js/main.js?v=2026-08-02-10',
    '/js/manualPage.js?v=2026-08-02-10',
    '/js/printPage.js?v=2026-08-02-10',
    '/js/quizPage.js?v=2026-08-02-10',
    '/js/registerServiceWorker.js?v=2026-08-02-10',
    '/js/zenPage.js?v=2026-08-02-10',
    '/site.webmanifest?v=2026-08-02-10',
];
// END GENERATED PRECACHE MANIFEST

function shouldRuntimeCache(url) {
    if (url.origin !== self.location.origin) return false;
    const { pathname } = url;
    const dot = pathname.lastIndexOf('.');
    if (dot === -1) return false;
    return CACHEABLE_EXTENSIONS.has(pathname.slice(dot).toLowerCase());
}

self.addEventListener('install', (event) => {
    event.waitUntil((async () => {
        const cache = await caches.open(APP_CACHE);
        // Precache each URL individually so one missing asset does not abort
        // the entire install. Failures are collected and logged, but install proceeds.
        const failures = [];
        await Promise.allSettled(
            PRECACHE_URLS.map((url) =>
                cache.add(url).catch((err) => {
                    failures.push(url);
                    console.warn(`[SW] precache miss: ${url}`, err);
                })
            )
        );
        if (failures.length > 0) {
            console.warn(`[SW] ${failures.length} precache entries failed:`, failures);
        }
        await self.skipWaiting();
    })());
});

self.addEventListener('activate', (event) => {
    event.waitUntil((async () => {
        const cacheNames = await caches.keys();
        // Delete any cache that is neither the current precache nor the current runtime cache.
        const keep = new Set([APP_CACHE, RUNTIME_CACHE]);
        await Promise.all(
            cacheNames
                .filter((cacheName) => !keep.has(cacheName))
                .map((cacheName) => caches.delete(cacheName))
        );
        await self.clients.claim();
    })());
});

async function trimRuntimeCache(cache) {
    try {
        const keys = await cache.keys();
        if (keys.length <= MAX_RUNTIME_CACHE_ENTRIES) return;
        // Remove oldest entries (front of the list) until within the limit.
        const toDelete = keys.slice(0, keys.length - MAX_RUNTIME_CACHE_ENTRIES);
        await Promise.all(toDelete.map((req) => cache.delete(req)));
    } catch {
        // Cache trimming is best-effort; quota errors should not break the page.
    }
}

async function updateRuntimeCache(request, response) {
    if (!response || response.status !== 200 || response.type !== 'basic') {
        return response;
    }

    if (!shouldRuntimeCache(new URL(request.url))) {
        return response;
    }

    try {
        // Use the dedicated RUNTIME_CACHE so trimming never evicts precache entries.
        const cache = await caches.open(RUNTIME_CACHE);
        await cache.put(request, response.clone());
        await trimRuntimeCache(cache);
    } catch {
        // cache.put can throw on quota exceeded or private browsing restrictions.
        // Failing to cache should never break the page response.
    }

    return response;
}

// caches.match searches all caches (APP_CACHE + RUNTIME_CACHE) by default.
// The pathname lookup only rescues navigations that carry a query string
// (e.g. /manual.html?lesson=loops -> /manual.html). Versioned CSS/JS URLs are
// deliberately NOT mirrored under their bare pathname in PRECACHE_URLS: a bare
// key would shadow a newer ?v= token and serve a stale asset, defeating cache
// busting. On an exact miss those assets must reach the network instead.
async function matchCachedRequest(request) {
    const exactMatch = await caches.match(request);
    if (exactMatch) return exactMatch;

    return caches.match(new URL(request.url).pathname);
}

// Response.error() keeps respondWith() from resolving to undefined when even the
// offline shell is missing from the cache.
async function matchOfflineShell() {
    return await caches.match(OFFLINE_FALLBACK_URL) || Response.error();
}

async function matchNavigationFallback(request) {
    const cachedResponse = await matchCachedRequest(request);
    if (cachedResponse) return cachedResponse;

    return matchOfflineShell();
}

async function handleNavigation(request) {
    try {
        const networkResponse = await fetch(request);
        return updateRuntimeCache(request, networkResponse);
    } catch {
        return matchNavigationFallback(request);
    }
}

async function handleStaticRequest(request) {
    const cachedResponse = await matchCachedRequest(request);
    if (cachedResponse) {
        return cachedResponse;
    }

    try {
        const networkResponse = await fetch(request);
        return updateRuntimeCache(request, networkResponse);
    } catch {
        if (request.destination === 'document') {
            return matchOfflineShell();
        }
        throw new Error(`Offline cache miss for ${request.url}`);
    }
}

self.addEventListener('fetch', (event) => {
    const { request } = event;

    if (request.method !== 'GET') {
        return;
    }

    const url = new URL(request.url);
    if (url.origin !== self.location.origin || url.pathname === '/sw.js') {
        return;
    }

    if (request.mode === 'navigate') {
        event.respondWith(handleNavigation(request));
        return;
    }

    event.respondWith(handleStaticRequest(request));
});
