name: ravlykonline
static_sites:
  - name: ravlykonline-github-io
    environment_slug: html
    github:
      repo: ravlykonline/ravlykonline.github.io
      branch: main
      deploy_on_push: true
    source_dir: /
    output_dir: .
    index_document: index.html
    routes:
      - path: /
